name: Teste de Update
run-name: ${{ github.actor }} realizou um deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Rodando o coiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SV_IP }}
          username: ${{ secrets.SV_USER }}
          key: ${{ secrets.SV_KEY }}
          port: 22
          script: |
            mkdir pastinha